name: Validate Benchmark Submission

on:
  pull_request:
    paths:
      - 'benchmarks/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install validation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pandas jsonschema

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Validate benchmark structure
        run: |
          python .github/scripts/validate_benchmark.py

      - name: Validate data files
        run: |
          python .github/scripts/validate_data.py

      - name: Check Quarto rendering
        uses: quarto-dev/quarto-actions/render@v2

      - name: Post validation results
        if: always()
        run: |
          echo "Validation completed. Check logs for details."
